{
 "title": "Borgmatic Backups",
 "description": "Dashboard for Borgmatic and Borgmatic Exporter",
 "tags": [ "backup" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Backup Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (repository) (borg_total_backups{job=\"borgmatic\"})"
    }
   ]
  },
  {
   "title": "Total Backup Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (repository) (borg_total_size{job=\"borgmatic\"})"
    }
   ]
  },
  {
   "title": "Total Deduplicated Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (repository) (borg_unique_size{job=\"borgmatic\"})"
    }
   ]
  },
  {
   "title": "Backup Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (repository) (borg_total_backups{job=\"borgmatic\"})",
     "legendFormat": "{{host}} backups"
    }
   ]
  },
  {
   "title": "Backups",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (repository) (borg_total_backups{job=\"borgmatic\"})\n"
    },
    {
     "expr": "sum by (repository) (borg_last_backup_timestamp{job=\"borgmatic\"}) * 1000\n"
    },
    {
     "expr": "time() - sum by (repository) (borg_last_backup_timestamp{job=\"borgmatic\"})\n"
    }
   ]
  },
  {
   "title": "Backup Total Sizes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (repository) (borg_total_size{job=\"borgmatic\"})",
     "legendFormat": "{{host}} raw size"
    },
    {
     "expr": "sum by (repository) (borg_unique_size{job=\"borgmatic\"})",
     "legendFormat": "{{host}} deduplicated size"
    }
   ]
  }
 ]
}