name: Nix Flake Check

on:
  push:
    branches:
      - main
      - forgejo
  pull_request:
  workflow_dispatch:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    container:
      image: forgejo.bobtail-clownfish.ts.net/bcotton/nix-ci-runner:c88527f
      options: --user root
    steps:
      - name: Setup SSH key for distributed builds
        run: |
          mkdir -p /run/secrets
          echo "${{ secrets.NIX_BUILDER_KEY }}" > /run/secrets/nix-builder-key
          chmod 600 /run/secrets/nix-builder-key

      - name: Setup Nix environment
        run: |
          # Configure git for flakes
          git config --global user.email "actions@forgejo.local"
          git config --global user.name "Forgejo Actions"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for better caching

      - name: Check Nix installation
        run: |
          nix --version
          git --version
          echo "Current directory: $(pwd)"
          echo "Git status:"
          git status || echo "Not a git repository or git not working"

      - name: Run nix flake check
        run: |
          echo "Running nix flake check..."
          nix flake check --show-trace

      - name: Show flake info
        if: success() || failure()
        run: |
          echo "=== Flake Info ==="
          nix flake info --json | head -20 || true
          echo ""
          echo "=== Flake Metadata ==="
          nix flake metadata || true

  build-hosts:
    runs-on: ubuntu-latest
    container:
      image: forgejo.bobtail-clownfish.ts.net/bcotton/nix-ci-runner:c88527f
      options: --user root
    steps:
      - name: Setup SSH key for distributed builds
        run: |
          mkdir -p /run/secrets
          echo "${{ secrets.NIX_BUILDER_KEY }}" > /run/secrets/nix-builder-key
          chmod 600 /run/secrets/nix-builder-key

      - name: Setup Nix environment
        run: |
          git config --global user.email "actions@forgejo.local"
          git config --global user.name "Forgejo Actions"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build all NixOS host configurations
        run: |
          echo "Building all NixOS host system closures..."
          hosts=$(nix eval --raw '.#nixosConfigurations' --apply 'x: builtins.concatStringsSep "\n" (builtins.attrNames x)')
          host_count=$(echo "$hosts" | wc -l)
          echo "Found $host_count hosts to build"
          echo ""

          # Build hosts in parallel (4 at a time) to utilize all builders
          mkdir -p /tmp/build-results
          echo "$hosts" | xargs -P4 -I{} bash -c '
            host="{}"
            log="/tmp/build-results/${host}.log"
            echo "Starting build: $host"
            if nix build ".#nixosConfigurations.${host}.config.system.build.toplevel" 2>"$log"; then
              echo "✓ $host built successfully"
              echo "ok" > "/tmp/build-results/${host}.status"
            else
              echo "✗ $host FAILED to build"
              echo "fail" > "/tmp/build-results/${host}.status"
            fi
          '

          # Report results
          echo ""
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Build Results:"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          failed=""
          for host in $hosts; do
            status=$(cat "/tmp/build-results/${host}.status" 2>/dev/null || echo "fail")
            if [ "$status" = "ok" ]; then
              echo "  ✓ $host"
            else
              echo "  ✗ $host FAILED"
              cat "/tmp/build-results/${host}.log" 2>/dev/null
              failed="$failed $host"
            fi
          done
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          if [ -n "$failed" ]; then
            echo "FAILED hosts:$failed"
            exit 1
          else
            echo "All $host_count hosts built successfully"
          fi