name: Nix Flake Check

on:
  push:
    branches:
      - main
      - forgejo
  pull_request:
  workflow_dispatch:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    container:
      image: forgejo.bobtail-clownfish.ts.net/bcotton/nix-ci-runner:c88527f
      options: --user root
    steps:
      - name: Setup SSH key for distributed builds
        run: |
          mkdir -p /run/secrets
          echo "${{ secrets.NIX_BUILDER_KEY }}" > /run/secrets/nix-builder-key
          chmod 600 /run/secrets/nix-builder-key

      - name: Setup Nix environment
        run: |
          # Configure git for flakes
          git config --global user.email "actions@forgejo.local"
          git config --global user.name "Forgejo Actions"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for better caching

      - name: Check Nix installation
        run: |
          nix --version
          git --version
          echo "Current directory: $(pwd)"
          echo "Git status:"
          git status || echo "Not a git repository or git not working"

      - name: Run nix flake check
        run: |
          echo "Running nix flake check..."
          nix flake check --show-trace

      - name: Show flake info
        if: success() || failure()
        run: |
          echo "=== Flake Info ==="
          nix flake info --json | head -20 || true
          echo ""
          echo "=== Flake Metadata ==="
          nix flake metadata || true

  build-hosts:
    runs-on: ubuntu-latest
    container:
      image: forgejo.bobtail-clownfish.ts.net/bcotton/nix-ci-runner:c88527f
      options: --user root
    steps:
      - name: Setup SSH key for distributed builds
        run: |
          mkdir -p /run/secrets
          echo "${{ secrets.NIX_BUILDER_KEY }}" > /run/secrets/nix-builder-key
          chmod 600 /run/secrets/nix-builder-key

      - name: Setup Nix environment
        run: |
          git config --global user.email "actions@forgejo.local"
          git config --global user.name "Forgejo Actions"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build all NixOS host configurations
        run: |
          echo "Building all NixOS host system closures..."
          hosts=$(nix eval --raw '.#nixosConfigurations' --apply 'x: builtins.concatStringsSep "\n" (builtins.attrNames x)')
          host_count=$(echo "$hosts" | wc -l)
          echo "Found $host_count hosts to build"

          # Pre-build diagnostics
          echo ""
          echo "::group::Nix store info (pre-build)"
          nix store info 2>&1 || true
          df -h /nix 2>/dev/null || true
          echo "::endgroup::"

          # Build hosts sequentially - remote builders handle parallelism internally
          mkdir -p /tmp/build-results
          total_start=$SECONDS
          failed=""
          succeeded=""

          for host in $hosts; do
            echo ""
            echo "::group::Build $host"

            # Dry-run to show cache hit stats
            echo "--- Dry-run for $host ---"
            drv=".#nixosConfigurations.${host}.config.system.build.toplevel"
            dry_output=$(nix build "$drv" --dry-run 2>&1) || true
            will_build=$(echo "$dry_output" | grep -c "will be built" || true)
            will_fetch=$(echo "$dry_output" | grep -c "will be fetched" || true)
            echo "  derivations to build: $will_build"
            echo "  store paths to fetch: $will_fetch"
            echo ""

            # Timed build
            host_start=$SECONDS
            if nix build "$drv" --out-link "/tmp/build-results/${host}.link" 2>&1; then
              elapsed=$(( SECONDS - host_start ))
              echo ""
              echo "OK $host built successfully in ${elapsed}s"
              echo "ok" > "/tmp/build-results/${host}.status"
              echo "$elapsed" > "/tmp/build-results/${host}.time"
              succeeded="$succeeded $host"
            else
              elapsed=$(( SECONDS - host_start ))
              echo ""
              echo "FAIL $host FAILED after ${elapsed}s"
              echo "fail" > "/tmp/build-results/${host}.status"
              echo "$elapsed" > "/tmp/build-results/${host}.time"
              failed="$failed $host"
            fi
            echo "::endgroup::"
          done

          total_elapsed=$(( SECONDS - total_start ))

          # Always print results summary
          echo ""
          echo "============================================"
          echo "Build Results (total: ${total_elapsed}s)"
          echo "============================================"
          for host in $hosts; do
            status=$(cat "/tmp/build-results/${host}.status" 2>/dev/null || echo "unknown")
            elapsed=$(cat "/tmp/build-results/${host}.time" 2>/dev/null || echo "?")
            if [ "$status" = "ok" ]; then
              echo "  OK  $host  (${elapsed}s)"
            else
              echo "  FAIL  $host  (${elapsed}s)"
            fi
          done
          echo "============================================"

          if [ -n "$failed" ]; then
            echo "FAILED hosts:$failed"
            exit 1
          else
            echo "All $host_count hosts built successfully in ${total_elapsed}s"
          fi

      - name: Push build results to binary cache
        if: always()
        run: |
          echo "Pushing successful build results to binary cache..."
          pushed=0
          push_failed=0

          for link in /tmp/build-results/*.link; do
            [ -e "$link" ] || continue
            host=$(basename "$link" .link)
            store_path=$(readlink -f "$link")
            echo "::group::Push $host ($store_path)"
            if nix copy --to ssh://nix-builder@nas-01.lan "$store_path" 2>&1; then
              echo "OK pushed $host to cache"
              pushed=$((pushed + 1))
            else
              echo "WARNING: failed to push $host to cache (non-fatal)"
              push_failed=$((push_failed + 1))
            fi
            echo "::endgroup::"
          done

          echo ""
          echo "Cache push: $pushed succeeded, $push_failed failed"