name: Playwright Tests

on:
  push:
    branches:
      - main
      - playwrite-in-nix
      - playwrite-cli-tests
  pull_request:
  workflow_dispatch:

jobs:
  playwright:
    runs-on: ubuntu-latest
    container:
      image: forgejo.bobtail-clownfish.ts.net/bcotton/nix-ci-runner:fe32792
      options: --user root --dns 100.100.100.100
    steps:
      - name: Setup Nix environment
        run: |
          git config --global user.email "actions@forgejo.local"
          git config --global user.name "Forgejo Actions"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup smoke test credentials
        run: |
          echo "${{ secrets.SMOKE_TEST_CREDS }}" > shells/playwright/.env

      - name: Enter Playwright shell and run tests
        run: |
          cd shells/playwright
          nix develop --command bash -c '
            echo "=== Playwright Environment ==="
            echo "Node version: $(node --version)"
            echo "Browser path: $PLAYWRIGHT_BROWSERS_PATH"
            echo "SSL_CERT_FILE: ${SSL_CERT_FILE:-unset}"
            echo ""

            # Install npm dependencies first
            npm ci

            echo "=== Chromium direct launch test (ignoreHTTPSErrors: true) ==="
            node -e "
              const { chromium } = require(\"@playwright/test\").default || require(\"playwright-core\");
              (async () => {
                const browser = await chromium.launch({
                  args: [\"--no-sandbox\", \"--disable-setuid-sandbox\", \"--disable-dev-shm-usage\", \"--disable-gpu\"]
                });
                const page = await browser.newPage({ ignoreHTTPSErrors: true });
                page.on(\"console\", msg => console.log(\"  PAGE CONSOLE:\", msg.type(), msg.text()));
                page.on(\"pageerror\", err => console.log(\"  PAGE ERROR:\", err.message));
                page.on(\"requestfailed\", req => console.log(\"  REQ FAILED:\", req.url(), req.failure()?.errorText));
                try {
                  console.log(\"Navigating to navidrome...\");
                  const resp = await page.goto(\"https://navidrome.bobtail-clownfish.ts.net/\", { timeout: 30000, waitUntil: \"domcontentloaded\" });
                  console.log(\"Response status:\", resp?.status());
                  console.log(\"Page URL:\", page.url());
                  console.log(\"Page title:\", await page.title());
                } catch(e) {
                  console.error(\"Navigation error:\", e.message);
                }
                await browser.close();
              })();
            " || true
            echo ""

            # Run only navidrome tests for CI debugging
            node node_modules/@playwright/test/cli.js test \
              --project=setup-navidrome --project=navidrome
          '

