name: Playwright Tests

on:
  push:
    branches:
      - main
      - playwrite-in-nix
      - playwrite-cli-tests
  pull_request:
  workflow_dispatch:

jobs:
  playwright:
    runs-on: ubuntu-latest
    container:
      image: forgejo.bobtail-clownfish.ts.net/bcotton/nix-ci-runner:fe32792
      options: --user root --ipc=host
    steps:
      - name: Setup Nix environment
        run: |
          git config --global user.email "actions@forgejo.local"
          git config --global user.name "Forgejo Actions"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup smoke test credentials
        run: |
          echo "${{ secrets.SMOKE_TEST_CREDS }}" > shells/playwright/.env

      - name: Enter Playwright shell and run tests
        timeout-minutes: 10
        run: |
          cd shells/playwright
          nix develop --command bash -c '
            echo "=== Playwright Environment ==="
            echo "Node version: $(node --version)"
            echo "Browser path: $PLAYWRIGHT_BROWSERS_PATH"
            echo "SSL_CERT_FILE: ${SSL_CERT_FILE:-unset}"
            echo ""

            # Install npm dependencies
            npm ci

            # Warm up Chromium (first launch in container can fail without this)
            node -e "
              const pw = require(\"playwright-core\");
              (async () => {
                const b = await pw.chromium.launch({args:[\"--no-sandbox\",\"--disable-dev-shm-usage\"]});
                const p = await b.newPage();
                await p.goto(\"data:text/html,<h1>ok</h1>\");
                console.log(\"Chromium warm-up OK\");
                await b.close();
              })();
            "

            # Run only navidrome tests for now
            node node_modules/@playwright/test/cli.js test \
              --project=setup-navidrome --project=navidrome
          '

