name: Playwright Tests

on:
  push:
    branches:
      - main
      - playwrite-in-nix
      - playwrite-cli-tests
  pull_request:
  workflow_dispatch:

jobs:
  playwright:
    runs-on: ubuntu-latest
    container:
      image: forgejo.bobtail-clownfish.ts.net/bcotton/nix-ci-runner:fe32792
      options: --user root --dns 100.100.100.100
    steps:
      - name: Setup Nix environment
        run: |
          git config --global user.email "actions@forgejo.local"
          git config --global user.name "Forgejo Actions"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup smoke test credentials
        run: |
          echo "${{ secrets.SMOKE_TEST_CREDS }}" > shells/playwright/.env

      - name: Network diagnostics
        run: |
          echo "=== Network Diagnostics ==="
          echo "--- /etc/resolv.conf ---"
          cat /etc/resolv.conf || true
          echo ""
          echo "--- DNS resolution via getent ---"
          getent hosts navidrome.bobtail-clownfish.ts.net || echo "getent failed"
          echo ""
          echo "--- Connectivity test via bash /dev/tcp ---"
          timeout 10 bash -c 'echo > /dev/tcp/navidrome.bobtail-clownfish.ts.net/443 && echo "TCP connect OK"' 2>&1 || echo "TCP connect FAILED"

      - name: Enter Playwright shell and run tests
        run: |
          cd shells/playwright
          nix develop --command bash -c '
            echo "=== Playwright Environment ==="
            echo "Node version: $(node --version)"
            echo "Browser path: $PLAYWRIGHT_BROWSERS_PATH"

            # Install npm dependencies
            npm ci

            # Run only navidrome tests for CI debugging
            node node_modules/@playwright/test/cli.js test \
              --project=setup-navidrome --project=navidrome
          '

