name: Playwright Tests

on:
  push:
    branches:
      - main
      - playwrite-in-nix
      - playwrite-cli-tests
  pull_request:
  workflow_dispatch:

jobs:
  playwright:
    runs-on: ubuntu-latest
    container:
      image: forgejo.bobtail-clownfish.ts.net/bcotton/nix-ci-runner:fe32792
      options: --user root --dns 100.100.100.100
    steps:
      - name: Setup Nix environment
        run: |
          git config --global user.email "actions@forgejo.local"
          git config --global user.name "Forgejo Actions"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup smoke test credentials
        run: |
          echo "${{ secrets.SMOKE_TEST_CREDS }}" > shells/playwright/.env

      - name: Enter Playwright shell and run tests
        run: |
          cd shells/playwright
          nix develop --command bash -c '
            echo "=== Playwright Environment ==="
            echo "Node version: $(node --version)"
            echo "Browser path: $PLAYWRIGHT_BROWSERS_PATH"
            echo "SSL_CERT_FILE: ${SSL_CERT_FILE:-unset}"
            echo "NODE_EXTRA_CA_CERTS: ${NODE_EXTRA_CA_CERTS:-unset}"
            echo ""

            echo "=== Node.js fetch test ==="
            node -e "
              fetch(\"https://navidrome.bobtail-clownfish.ts.net/\")
                .then(r => console.log(\"Node fetch: HTTP\", r.status))
                .catch(e => console.error(\"Node fetch error:\", e.message, e.cause || \"\"));
            " || true
            echo ""

            echo "=== Chromium direct launch test ==="
            node -e "
              const { chromium } = require(\"playwright\");
              (async () => {
                const browser = await chromium.launch({
                  args: [\"--no-sandbox\", \"--disable-setuid-sandbox\", \"--disable-dev-shm-usage\", \"--disable-gpu\"]
                });
                const page = await browser.newPage({ ignoreHTTPSErrors: true });
                try {
                  const resp = await page.goto(\"https://navidrome.bobtail-clownfish.ts.net/\", { timeout: 30000 });
                  console.log(\"Chromium status:\", resp?.status());
                  console.log(\"Chromium url:\", page.url());
                } catch(e) {
                  console.error(\"Chromium error:\", e.message);
                }
                await browser.close();
              })();
            " || true
            echo ""

            # Install npm dependencies
            npm ci

            # Run only navidrome tests for CI debugging
            node node_modules/@playwright/test/cli.js test \
              --project=setup-navidrome --project=navidrome
          '

