name: Playwright Tests

on:
  push:
    branches:
      - main
      - playwrite-in-nix
      - playwrite-cli-tests
  pull_request:
  workflow_dispatch:

jobs:
  playwright:
    runs-on: ubuntu-latest
    container:
      image: forgejo.bobtail-clownfish.ts.net/bcotton/nix-ci-runner:fe32792
      options: --user root --ipc=host --cap-add=NET_ADMIN --device /dev/net/tun
    steps:
      - name: Setup Nix environment
        run: |
          git config --global user.email "actions@forgejo.local"
          git config --global user.name "Forgejo Actions"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup smoke test credentials
        run: |
          echo "${{ secrets.SMOKE_TEST_CREDS }}" > shells/playwright/.env

      - name: Enter Playwright shell and run tests
        timeout-minutes: 10
        run: |
          cd shells/playwright
          nix develop --command bash -c '
            echo "=== Playwright Environment ==="
            echo "Node version: $(node --version)"
            echo "Browser path: $PLAYWRIGHT_BROWSERS_PATH"
            echo "SSL_CERT_FILE: ${SSL_CERT_FILE:-unset}"
            echo ""

            # Install npm dependencies
            npm ci

            # Diagnostic: does playwright-core crash with waitUntil:load?
            timeout 60 node -e "
              const pw = require(\"playwright-core\");
              (async () => {
                const b = await pw.chromium.launch({args:[\"--no-sandbox\",\"--disable-dev-shm-usage\",\"--disable-gpu\"]});
                const p = await b.newPage({ignoreHTTPSErrors:true});
                p.on(\"crash\", () => console.error(\"DIAG: PAGE CRASHED\"));
                console.log(\"DIAG: navigating with waitUntil:load...\");
                const r = await p.goto(\"https://navidrome.bobtail-clownfish.ts.net/\",{timeout:20000,waitUntil:\"load\"});
                console.log(\"DIAG: goto done:\",r?.status(),p.url());
                await new Promise(r => setTimeout(r, 5000));
                console.log(\"DIAG: no crash after 5s, URL:\",p.url());
                await b.close();
              })().catch(e=>console.error(\"DIAG error:\",e.message?.split(String.fromCharCode(10))[0]));
            " || echo "Diagnostic timed out (non-fatal)"

            # Run only navidrome tests for now
            node node_modules/@playwright/test/cli.js test \
              --project=setup-navidrome --project=navidrome
          '

