version: "3.7"
name: audiobookshelf
services:
  tailscale:
    hostname: books
    image: tailscale/tailscale:latest
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /mnt/docker_volumes/tailscale/audobookshelf:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /mnt/docker_volumes/audiobookshelf/audiobooks:/audiobooks
      - /mnt/docker_volumes/audiobookshelf/podcasts:/podcasts
      - /mnt/docker_volumes/audiobookshelf/config:/config
      - /mnt/docker_volumes/audiobookshelf/metadata:/metadata
    depends_on:
      - tailscale
    network_mode: service:tailscale

  # volumes:
  #   /mnt/docker_volumes/tailscale/audobookshelf:
  #     driver: local
