name: Flake Check

on:
  push:
    branches:
      - '**'

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: extractions/setup-just@v1
        with:
          just-version: '1.14.0'  # Optional: specify a version
      - name: Run flake check
        run: just check
