name: Flake Check

on:
  push:
    branches:
      - '**'

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run flake check
        run: nix build '.#checks.x86_64-linux.postgresql'
        # run: nix flake check
